### ISSUE TITLE
Can't inject when device 64bit and target app 32bit

### ISSUE THREAD

**Issue by im-baydroid** [SsageParuders/AndroidPtraceInject#1]
What is wrong ?

**Case 1**

Device: A11-64bit (arm)
Inject: armeabi-v7a
libHook: armeabi-v7a
Target App: armeabi-v7a
Result: Inject error ×

**Case 2**

Device: A11-64bit (arm)
Inject: arm64-v8a
libHook: arm64-v8a
Target App: arm64-v8a
Result: Inject success ✓

Sory im noob about ptrace.

**Comment by SsageParuders** [comment]
Sorry, there is a bug, I will try to fix it.

**Comment by SsageParuders** [comment]
> What is wrong ?
> 
> **Case 1**
> 
> Device: A11-64bit (arm) Inject: armeabi-v7a libHook: armeabi-v7a Target App: armeabi-v7a Result: Inject error ×
> 
> **Case 2**
> 
> Device: A11-64bit (arm) Inject: arm64-v8a libHook: arm64-v8a Target App: arm64-v8a Result: Inject success ✓
> 
> Sory im noob about ptrace.

Sorry, there is a bug, I will try to fix it.
Now, u can have a try with [Adrill](https://github.com/mustime/Adrill)

**Comment by im-baydroid** [comment]
Okay thanks, I will wait for the good news.

> > What is wrong ?
> > **Case 1**
> > Device: A11-64bit (arm) Inject: armeabi-v7a libHook: armeabi-v7a Target App: armeabi-v7a Result: Inject error ×
> > **Case 2**
> > Device: A11-64bit (arm) Inject: arm64-v8a libHook: arm64-v8a Target App: arm64-v8a Result: Inject success ✓
> > Sory im noob about ptrace.
> 
> Sorry, there is a bug, I will try to fix it. Now, u can have a try with [Adrill](https://github.com/mustime/Adrill)

**Comment by SsageParuders** [comment]
> Okay thanks, I will wait for the good news.
> 
> > > What is wrong ?
> > > **Case 1**
> > > Device: A11-64bit (arm) Inject: armeabi-v7a libHook: armeabi-v7a Target App: armeabi-v7a Result: Inject error ×
> > > **Case 2**
> > > Device: A11-64bit (arm) Inject: arm64-v8a libHook: arm64-v8a Target App: arm64-v8a Result: Inject success ✓
> > > Sory im noob about ptrace.
> > 
> > 
> > Sorry, there is a bug, I will try to fix it. Now, u can have a try with [Adrill](https://github.com/mustime/Adrill)

I have made tests for both Android9_arm32 and Android11_arm32.
Android 11 was a success but Android 9 failed.
Btw, what 's your Android version?

**Comment by SsageParuders** [comment]
Try to start app manually, and use Inject without `-f`?
How about this log?
